<?php

namespace App\Http\Controllers;

use App\Models\InventoryItem;
use App\Models\InventoryItemHistory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Schema;
use Inertia\Inertia;

class InventoryController extends Controller
{
    /**
     * ============================================================
     * INVENTORY PAGE
     * ============================================================
     */
    public function index()
    {
        $inventoryItems = InventoryItem::query()
            ->orderByRaw("
                CASE
                    WHEN LOWER(TRIM(category)) = 'supplies' THEN 1
                    WHEN LOWER(TRIM(category)) = 'ict' THEN 2
                    ELSE 3
                END
            ")
            ->orderBy('item')
            ->get()
            ->map(function ($item) {
                return [
                    'id' => $item->id,

                    /**
                     * Vue expects exactly:
                     * supplies
                     * ict
                     */
                    'category' => strtolower(
                        trim((string) $item->category)
                    ),

                    'item' => $item->item,

                    'unit' => strtoupper(
                        trim((string) $item->unit)
                    ),

                    /**
                     * Starting / reference quantity.
                     */
                    'fixed_value' =>
                        $item->fixed_value !== null
                            ? (int) $item->fixed_value
                            : null,

                    /**
                     * Actual physical stock currently
                     * available in SPD.
                     */
                    'currently_available' =>
                        $item->currently_available !== null
                            ? (int) $item->currently_available
                            : null,

                    /**
                     * GENERATED BY MYSQL:
                     *
                     * fixed_value - currently_available
                     *
                     * Read only. Never save/update this
                     * manually from Laravel.
                     */
                    'total_released' =>
                        $item->total_released !== null
                            ? (int) $item->total_released
                            : null,

                    'quarters' => $item->quarters,
                    'ppmp' => $item->ppmp,
                    'remarks' => $item->remarks,

                    'created_at' => $item->created_at,
                    'updated_at' => $item->updated_at,
                ];
            })
            ->values();

        return Inertia::render('DTS/Inventory', [
            'inventoryItems' => $inventoryItems,
        ]);
    }


    /**
     * ============================================================
     * ADD ITEM
     * ============================================================
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'category' => [
                'required',
                'in:supplies,ict',
            ],

            'item' => [
                'required',
                'string',
                'max:255',
            ],

            'unit' => [
                'required',
                'string',
                'max:50',
            ],

            /**
             * Reference / starting quantity.
             */
            'fixed_value' => [
                'nullable',
                'integer',
                'min:0',
            ],

            /**
             * Actual current physical quantity.
             */
            'currently_available' => [
                'required',
                'integer',
                'min:0',
            ],

            'quarters' => [
                'nullable',
                'array',
            ],

            'quarters.*' => [
                'in:q1,q2,q3,q4',
            ],

            'ppmp' => [
                'nullable',
                'string',
            ],

            'remarks' => [
                'nullable',
                'string',
            ],
        ]);

        /**
         * Normalize values.
         */
        $validated['category'] = strtolower(
            trim($validated['category'])
        );

        $validated['unit'] = strtoupper(
            trim($validated['unit'])
        );

        /**
         * IMPORTANT:
         *
         * Do NOT add:
         *
         * $validated['total_released']
         *
         * because total_released is generated
         * automatically by MySQL.
         */
        $inventoryItem = InventoryItem::create(
            $validated
        );

        Log::info('Inventory item created', [
            'inventory_item_id' =>
                $inventoryItem->id,

            'item' =>
                $inventoryItem->item,

            'category' =>
                $inventoryItem->category,

            'fixed_value' =>
                $inventoryItem->fixed_value,

            'currently_available' =>
                $inventoryItem->currently_available,
        ]);

        return back()->with(
            'success',
            'Inventory item added successfully.'
        );
    }


    /**
     * ============================================================
     * UPDATE / RELEASE ITEM
     * ============================================================
     *
     * Release example:
     *
     * Fixed Value         = 30
     * Currently Available = 11
     * Quantity Released   = 19
     *
     * User releases 3:
     *
     * Currently Available = 8
     * Quantity Released   = 22 automatically
     *
     */
    public function update(
        Request $request,
        InventoryItem $inventoryItem
    ) {
        $validated = $request->validate([
            /**
             * Release modal sends this.
             */
            'release_quantity' => [
                'sometimes',
                'required',
                'integer',
                'min:1',
            ],

            /**
             * These fields are still supported
             * if we edit inventory information later.
             */
            'category' => [
                'sometimes',
                'required',
                'in:supplies,ict',
            ],

            'item' => [
                'sometimes',
                'required',
                'string',
                'max:255',
            ],

            'unit' => [
                'sometimes',
                'required',
                'string',
                'max:50',
            ],

            'fixed_value' => [
                'sometimes',
                'nullable',
                'integer',
                'min:0',
            ],

            'currently_available' => [
                'sometimes',
                'nullable',
                'integer',
                'min:0',
            ],

            'quarters' => [
                'sometimes',
                'nullable',
                'array',
            ],

            'quarters.*' => [
                'in:q1,q2,q3,q4',
            ],

            'ppmp' => [
                'sometimes',
                'nullable',
                'string',
            ],

            'remarks' => [
                'sometimes',
                'nullable',
                'string',
            ],
        ]);

        $user = $request->user();

        $userId = $user?->getKey();

        $userName =
            $user?->name
            ?? $user?->loginname
            ?? $user?->username
            ?? $user?->email
            ?? 'Unknown User';


        DB::transaction(function () use (
            $inventoryItem,
            $validated,
            $userId,
            $userName
        ) {
            /**
             * Lock the current item so two users cannot
             * release the same stock at exactly the same time.
             */
            $item = InventoryItem::query()
                ->whereKey($inventoryItem->id)
                ->lockForUpdate()
                ->firstOrFail();


            $oldCurrentlyAvailable =
                $item->currently_available !== null
                    ? (int) $item->currently_available
                    : 0;

            $oldTotalReleased =
                $item->total_released !== null
                    ? (int) $item->total_released
                    : 0;

            $oldRemarks =
                $item->remarks;


            /**
             * ====================================================
             * RELEASE INVENTORY
             * ====================================================
             */
            if (
                array_key_exists(
                    'release_quantity',
                    $validated
                )
            ) {
                $releaseQuantity =
                    (int) $validated['release_quantity'];

                if (
                    $releaseQuantity
                    > $oldCurrentlyAvailable
                ) {
                    abort(
                        422,
                        "Only {$oldCurrentlyAvailable} item(s) are currently available."
                    );
                }

                /**
                 * ONLY CURRENT STOCK IS CHANGED.
                 *
                 * total_released automatically changes
                 * because MySQL calculates:
                 *
                 * fixed_value - currently_available
                 */
                $item->currently_available =
                    $oldCurrentlyAvailable
                    - $releaseQuantity;
            }


            /**
             * ====================================================
             * OTHER EDITABLE FIELDS
             * ====================================================
             */
            if (
                array_key_exists(
                    'category',
                    $validated
                )
            ) {
                $item->category = strtolower(
                    trim($validated['category'])
                );
            }

            if (
                array_key_exists(
                    'item',
                    $validated
                )
            ) {
                $item->item =
                    trim($validated['item']);
            }

            if (
                array_key_exists(
                    'unit',
                    $validated
                )
            ) {
                $item->unit = strtoupper(
                    trim($validated['unit'])
                );
            }

            if (
                array_key_exists(
                    'fixed_value',
                    $validated
                )
            ) {
                $item->fixed_value =
                    $validated['fixed_value'];
            }

            /**
             * Direct inventory correction.
             *
             * This is separate from release_quantity.
             */
            if (
                !array_key_exists(
                    'release_quantity',
                    $validated
                )
                &&
                array_key_exists(
                    'currently_available',
                    $validated
                )
            ) {
                $item->currently_available =
                    $validated['currently_available'];
            }

            if (
                array_key_exists(
                    'quarters',
                    $validated
                )
            ) {
                $item->quarters =
                    $validated['quarters'];
            }

            if (
                array_key_exists(
                    'ppmp',
                    $validated
                )
            ) {
                $item->ppmp =
                    $validated['ppmp'];
            }

            if (
                array_key_exists(
                    'remarks',
                    $validated
                )
            ) {
                $item->remarks =
                    $validated['remarks'];
            }


            $newCurrentlyAvailable =
                $item->currently_available !== null
                    ? (int) $item->currently_available
                    : 0;

            $newRemarks =
                $item->remarks;


            $currentChanged =
                $oldCurrentlyAvailable
                !==
                $newCurrentlyAvailable;

            $remarksChanged =
                (string) ($oldRemarks ?? '')
                !==
                (string) ($newRemarks ?? '');


            /**
             * Save Inventory Item first.
             *
             * MySQL recalculates total_released
             * automatically here.
             */
            $item->save();

            /**
             * Reload generated total_released.
             */
            $item->refresh();

            $newTotalReleased =
                $item->total_released !== null
                    ? (int) $item->total_released
                    : 0;


            /**
             * ====================================================
             * INVENTORY HISTORY
             * ====================================================
             */
            if (
                $currentChanged
                || $remarksChanged
            ) {
                $history =
                    new InventoryItemHistory();

                $history->inventory_item_id =
                    $item->id;


                /**
                 * New history columns.
                 */
                if (
                    Schema::hasColumn(
                        'inventory_item_histories',
                        'old_currently_available'
                    )
                ) {
                    $history->old_currently_available =
                        $oldCurrentlyAvailable;
                }

                if (
                    Schema::hasColumn(
                        'inventory_item_histories',
                        'new_currently_available'
                    )
                ) {
                    $history->new_currently_available =
                        $newCurrentlyAvailable;
                }

                if (
                    Schema::hasColumn(
                        'inventory_item_histories',
                        'old_total_released'
                    )
                ) {
                    $history->old_total_released =
                        $oldTotalReleased;
                }

                if (
                    Schema::hasColumn(
                        'inventory_item_histories',
                        'new_total_released'
                    )
                ) {
                    $history->new_total_released =
                        $newTotalReleased;
                }


                /**
                 * Backward compatibility if your
                 * old history columns still exist.
                 *
                 * Store CURRENT AVAILABLE,
                 * not Quantity Released.
                 */
                if (
                    Schema::hasColumn(
                        'inventory_item_histories',
                        'old_available'
                    )
                ) {
                    $history->old_available =
                        $oldCurrentlyAvailable;
                }

                if (
                    Schema::hasColumn(
                        'inventory_item_histories',
                        'new_available'
                    )
                ) {
                    $history->new_available =
                        $newCurrentlyAvailable;
                }


                if (
                    Schema::hasColumn(
                        'inventory_item_histories',
                        'old_remarks'
                    )
                ) {
                    $history->old_remarks =
                        $oldRemarks;
                }

                if (
                    Schema::hasColumn(
                        'inventory_item_histories',
                        'new_remarks'
                    )
                ) {
                    $history->new_remarks =
                        $newRemarks;
                }

                if (
                    Schema::hasColumn(
                        'inventory_item_histories',
                        'updated_by'
                    )
                ) {
                    $history->updated_by =
                        $userId;
                }

                if (
                    Schema::hasColumn(
                        'inventory_item_histories',
                        'updated_by_name'
                    )
                ) {
                    $history->updated_by_name =
                        $userName;
                }

                $history->save();
            }


            Log::info(
                'Inventory item updated',
                [
                    'inventory_item_id' =>
                        $item->id,

                    'fixed_value' =>
                        $item->fixed_value,

                    'old_currently_available' =>
                        $oldCurrentlyAvailable,

                    'new_currently_available' =>
                        $newCurrentlyAvailable,

                    'old_total_released' =>
                        $oldTotalReleased,

                    'new_total_released' =>
                        $newTotalReleased,

                    'updated_by' =>
                        $userId,

                    'updated_by_name' =>
                        $userName,
                ]
            );
        });


        return back()->with(
            'success',
            'Inventory item updated successfully.'
        );
    }


    /**
     * ============================================================
     * INVENTORY HISTORY
     * ============================================================
     */
    public function history(
        InventoryItem $inventoryItem
    ) {
        $histories = $inventoryItem
            ->histories()
            ->latest('id')
            ->get()
            ->map(function ($history) {
                return [
                    'id' =>
                        $history->id,


                    /**
                     * NEW FIELD NAMES
                     */
                    'old_currently_available' =>
                        $history->old_currently_available
                        ??
                        $history->old_available
                        ??
                        $history->legacy_old_available,

                    'new_currently_available' =>
                        $history->new_currently_available
                        ??
                        $history->new_available
                        ??
                        $history->legacy_new_available,

                    'old_total_released' =>
                        $history->old_total_released,

                    'new_total_released' =>
                        $history->new_total_released,


                    /**
                     * Keep these aliases temporarily
                     * for older Vue history helpers.
                     */
                    'old_available' =>
                        $history->old_currently_available
                        ??
                        $history->old_available
                        ??
                        $history->legacy_old_available,

                    'new_available' =>
                        $history->new_currently_available
                        ??
                        $history->new_available
                        ??
                        $history->legacy_new_available,


                    'old_remarks' =>
                        $history->old_remarks,

                    'new_remarks' =>
                        $history->new_remarks,

                    'updated_by' =>
                        $history->updated_by,

                    'updated_by_name' =>
                        $history->updated_by_name,

                    'created_at' =>
                        $history->created_at
                            ?->timezone(
                                'Asia/Manila'
                            )
                            ->format(
                                'M d, Y h:i A'
                            ),
                ];
            });


        return response()->json([
            'item' => [
                'id' =>
                    $inventoryItem->id,

                'category' =>
                    strtolower(
                        trim(
                            (string)
                            $inventoryItem->category
                        )
                    ),

                'item' =>
                    $inventoryItem->item,

                'unit' =>
                    $inventoryItem->unit,

                'fixed_value' =>
                    $inventoryItem->fixed_value,

                /**
                 * Actual remaining physical stock.
                 */
                'currently_available' =>
                    $inventoryItem
                        ->currently_available,

                /**
                 * Generated quantity released.
                 */
                'total_released' =>
                    $inventoryItem
                        ->total_released,

                'remarks' =>
                    $inventoryItem->remarks,
            ],

            'histories' =>
                $histories,
        ]);
    }


    /**
     * ============================================================
     * DELETE ITEM
     * ============================================================
     */
    public function destroy(
        InventoryItem $inventoryItem
    ) {
        $inventoryItem->delete();

        return back()->with(
            'success',
            'Inventory item deleted successfully.'
        );
    }
}