<?php

namespace App\Http\Controllers;

use App\Models\InventoryItem;
use App\Models\InventoryItemHistory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Schema;
use Illuminate\Validation\ValidationException;
use Inertia\Inertia;

class InventoryController extends Controller
{
    /**
     * Inventory page.
     */
    public function index(Request $request)
    {
        return Inertia::render('DTS/Inventory', [
            'canManageInventory' =>
                $this->canManageInventory(
                    $request->user()
                ),

            'inventoryItems' => InventoryItem::query()
                ->orderByRaw("
                    CASE
                        WHEN LOWER(TRIM(category)) = 'supplies' THEN 1
                        WHEN LOWER(TRIM(category)) = 'ict' THEN 2
                        WHEN LOWER(TRIM(category)) = 'furniture' THEN 3
                        WHEN LOWER(TRIM(category)) = 'fixtures' THEN 4
                        WHEN LOWER(TRIM(category)) = 'emergency_kits' THEN 5
                        WHEN LOWER(TRIM(category)) = 'token_giveaways' THEN 6
                        ELSE 7
                    END
                ")
                ->orderBy('item')
                ->get(),
        ]);
    }

    /**
     * Add a new Supplies, ICT, or Other Items record.
     *
     * SUPPLIES
     * - Fixed Value is optional.
     * - Currently Available is required.
     * - If Fixed Value exists (> 0):
     *      Quantity Released = Fixed - Current (generated by MySQL)
     * - If Fixed Value is missing / 0:
     *      tracked_released starts at 0 and future releases accumulate there.
     *
     * ICT
     * - Normal items: Item, Unit, Count, Inventory Year, Quarter(s), Remarks.
     * - Subscription: Unit = MONTH or YEAR and currently_available stores duration.
     * - History is supported for ICT changes.
     *
     * OTHER ITEMS
     * - Furniture / Fixtures / Emergency Kits / Token and Giveaways:
     *   Item, Count (stored in currently_available), Location, Remarks.
     * - All Other Items use Count, Release, and History.
     */
    public function store(Request $request)
    {
        $this->authorizeInventoryManagement(
            $request
        );

        $validated = $request->validate([
            'category' => 'required|in:supplies,ict,furniture,fixtures,emergency_kits,token_giveaways',
            'item' => 'required|string|max:255',
            'location' =>
                'required_if:category,furniture,fixtures,emergency_kits,token_giveaways|nullable|string|max:255',
            'unit' =>
                'required_if:category,supplies,ict|nullable|string|max:50',
            'inventory_year' =>
                'required_if:category,supplies,ict|nullable|integer|min:2026|max:2100',
            'fixed_value' => 'nullable|integer|min:0',
            'currently_available' =>
                'required_if:category,furniture,fixtures,emergency_kits,token_giveaways|nullable|integer|min:0',
            'quarters' =>
                'required_if:category,supplies,ict|nullable|array|min:1',
            'quarters.*' => 'in:q1,q2,q3,q4',
            'quarter_stock' =>
                'required_if:category,supplies,ict|nullable|array',
            'quarter_stock.*' =>
                'array',
            'quarter_stock.*.current' =>
                'required|integer|min:0',
            'remarks' => 'nullable|string',
        ]);

        $validated['category'] =
            strtolower(trim($validated['category']));

        $otherCategories = [
            'furniture',
            'fixtures',
            'emergency_kits',
            'token_giveaways',
        ];

        $isOtherItem =
            in_array(
                $validated['category'],
                $otherCategories,
                true
            );

        if ($isOtherItem) {
            /*
             * Compatibility-only internal values.
             * These are NEVER shown or filtered in the Other Items UI.
             * The existing schema requires Unit / Year / Quarter values.
             */
            $validated['location'] =
                trim((string) $validated['location']);

            $validated['currently_available'] =
                (int) $validated['currently_available'];

            $validated['unit'] = 'N/A';
            $validated['inventory_year'] =
                max(2026, (int) now()->year);
            $validated['quarters'] = [
                'q1',
                'q2',
                'q3',
                'q4',
            ];

            $validated['fixed_value'] = null;
            $validated['quarter_stock'] = null;
        } else {
            $validated['location'] = null;

            $validated['unit'] =
                strtoupper(trim($validated['unit']));

            $quarters =
                $this->normalizedQuarterList(
                    $validated['quarters'] ?? []
                );

            $quarterStock =
                $this->buildQuarterStock(
                    $quarters,
                    $validated['quarter_stock'] ?? [],
                    null
                );

            $validated['quarters'] =
                $quarters;

            $validated['quarter_stock'] =
                $quarterStock;

            $validated['currently_available'] =
                $this->quarterStockCurrentTotal(
                    $quarterStock
                );

            if ($validated['category'] !== 'supplies') {
                $validated['fixed_value'] = null;
            }
        }

        /*
         * Never send total_released or tracked_released from the form.
         * - total_released is generated by MySQL.
         * - tracked_released starts at DB default 0.
         */
        InventoryItem::create($validated);

        return back()->with(
            'success',
            'Inventory item added successfully.'
        );
    }

    /**
     * Update / release an inventory item.
     */
    public function update(
        Request $request,
        InventoryItem $inventoryItem
    ) {
        $this->authorizeInventoryManagement(
            $request
        );

        $validated = $request->validate([
            'release_quantity' =>
                'sometimes|required|integer|min:1',

            'release_destination' =>
                'sometimes|nullable|string|max:255',

            'release_quarter' =>
                'sometimes|nullable|in:q1,q2,q3,q4',

            'category' =>
                'sometimes|required|in:supplies,ict,furniture,fixtures,emergency_kits,token_giveaways',

            'item' =>
                'sometimes|required|string|max:255',

            'location' =>
                'sometimes|nullable|string|max:255',

            'unit' =>
                'sometimes|required|string|max:50',

            'inventory_year' =>
                'sometimes|required|integer|min:2026|max:2100',

            'fixed_value' =>
                'sometimes|nullable|integer|min:0',

            'currently_available' =>
                'sometimes|nullable|integer|min:0',

            'quarters' =>
                'sometimes|required|array|min:1',

            'quarters.*' =>
                'in:q1,q2,q3,q4',

            'quarter_stock' =>
                'sometimes|nullable|array',

            'quarter_stock.*' =>
                'array',

            'quarter_stock.*.current' =>
                'required|integer|min:0',

            'remarks' =>
                'sometimes|nullable|string',
        ]);

        $user = $request->user();

        $userId = $user?->getKey();

        $userName =
            $user?->name
            ?? $user?->loginname
            ?? $user?->username
            ?? $user?->email
            ?? 'Unknown User';

        DB::transaction(function () use (
            $inventoryItem,
            $validated,
            $userId,
            $userName
        ) {
            /*
             * Lock the row so simultaneous releases cannot overdraw stock.
             */
            $item = InventoryItem::query()
                ->whereKey($inventoryItem->id)
                ->lockForUpdate()
                ->firstOrFail();

            /*
             * Full audit snapshot BEFORE any edit/release changes.
             * This lets History record Item Name, Unit, Year, Quarter(s),
             * Fixed Value, Currently Available, Remarks, etc.
             */
            $historyOldData =
                $this->inventoryHistorySnapshot($item);

            $category =
                strtolower(trim((string) $item->category));

            $oldCurrent =
                $item->currently_available !== null
                    ? (int) $item->currently_available
                    : null;

            $oldTrackedReleased =
                (int) ($item->tracked_released ?? 0);

            $oldHasFixedBaseline =
                $item->fixed_value !== null
                && (int) $item->fixed_value > 0;

            $oldDisplayedReleased =
                $oldHasFixedBaseline
                    && $oldCurrent !== null
                        ? max(
                            0,
                            (int) $item->fixed_value
                            - $oldCurrent
                        )
                        : $oldTrackedReleased;

            $oldRemarks =
                $item->remarks;

            $isRelease =
                array_key_exists(
                    'release_quantity',
                    $validated
                );

            /*
             * A remark entered in the Release modal belongs to
             * that release transaction. It must not become the
             * permanent item remark or reappear next time.
             */
            $releaseRemarks =
                $isRelease
                    ? trim(
                        (string) (
                            $validated['remarks']
                            ?? ''
                        )
                    )
                    : '';

            $releaseDestination =
                $isRelease
                    ? trim(
                        (string) (
                            $validated['release_destination']
                            ?? ''
                        )
                    )
                    : '';

            if (!$isRelease) {
                $targetCategory = strtolower(
                    trim((string) ($validated['category'] ?? $item->category))
                );

                $targetItemName = trim(
                    (string) ($validated['item'] ?? $item->item)
                );

                $otherCategories = [
                    'furniture',
                    'fixtures',
                    'emergency_kits',
                    'token_giveaways',
                ];

                $targetIsOther =
                    in_array(
                        $targetCategory,
                        $otherCategories,
                        true
                    );

                $targetLocation = trim(
                    (string) (
                        $validated['location']
                        ?? $item->location
                        ?? ''
                    )
                );

                $targetUnit = strtoupper(
                    trim((string) ($validated['unit'] ?? $item->unit))
                );

                $targetYear = (int) (
                    $validated['inventory_year']
                    ?? $item->inventory_year
                    ?? 2026
                );

                if (
                    $targetIsOther
                    && $targetLocation === ''
                ) {
                    throw ValidationException::withMessages([
                        'location' =>
                            'Location is required for Other Items.',
                    ]);
                }


                $targetRequiresCount =
                    in_array(
                        $targetCategory,
                        [
                            'furniture',
                            'fixtures',
                            'emergency_kits',
                            'token_giveaways',
                        ],
                        true
                    );

                $targetItemCount =
                    $validated['currently_available']
                    ?? $item->currently_available
                    ?? null;

                if (
                    $targetRequiresCount
                    && (
                        $targetItemCount === null
                        || (int) $targetItemCount < 0
                    )
                ) {
                    throw ValidationException::withMessages([
                        'currently_available' =>
                            'Count is required for this category.',
                    ]);
                }

                $duplicateQuery = InventoryItem::query()
                    ->where('id', '!=', $item->id)
                    ->whereRaw(
                        'LOWER(TRIM(category)) = ?',
                        [$targetCategory]
                    )
                    ->whereRaw(
                        'LOWER(TRIM(item)) = ?',
                        [strtolower($targetItemName)]
                    );

                if ($targetIsOther) {
                    $duplicateQuery->whereRaw(
                        'LOWER(TRIM(COALESCE(location, ""))) = ?',
                        [strtolower($targetLocation)]
                    );
                } else {
                    $duplicateQuery
                        ->whereRaw(
                            'UPPER(TRIM(unit)) = ?',
                            [$targetUnit]
                        )
                        ->where(
                            'inventory_year',
                            $targetYear
                        );
                }

                if ($duplicateQuery->exists()) {
                    throw ValidationException::withMessages([
                        'item' =>
                            $targetIsOther
                                ? 'This item already exists in the same location.'
                                : "This item and unit already exist for {$targetYear}.",
                    ]);
                }
            }
            /**
             * ========================================================
             * RELEASE QUANTITY / DURATION
             * ========================================================
             *
             * Supplies + ICT are quarter-aware.
             * Releases automatically use the latest assigned quarter.
             * Previous quarter balances remain historical snapshots.
             * Other counted items keep their existing global Count flow.
             */
            if (
                array_key_exists(
                    'release_quantity',
                    $validated
                )
            ) {
                $releaseableCategories = [
                    'supplies',
                    'ict',
                    'furniture',
                    'fixtures',
                    'emergency_kits',
                    'token_giveaways',
                ];

                if (
                    !in_array(
                        $category,
                        $releaseableCategories,
                        true
                    )
                ) {
                    throw ValidationException::withMessages([
                        'release_quantity' =>
                            'This inventory category does not use quantity release tracking.',
                    ]);
                }

                /*
                 * Supplies only need quantity + optional remarks.
                 * ICT and counted Other Items still require destination.
                 */
                if (
                    $category !== 'supplies'
                    && $releaseDestination === ''
                ) {
                    throw ValidationException::withMessages([
                        'release_destination' =>
                            'Released To / Destination is required.',
                    ]);
                }

                $releaseQuantity =
                    (int) $validated['release_quantity'];

                $usesQuarterStock =
                    in_array(
                        $category,
                        ['supplies', 'ict'],
                        true
                    );

                if ($usesQuarterStock) {
                    $assignedQuarters =
                        $this->normalizedQuarterList(
                            is_array($item->quarters)
                                ? $item->quarters
                                : []
                        );

                    $storedQuarterStock =
                        $this->normalizedStoredQuarterStock(
                            $item->quarter_stock
                        );

                    /*
                     * No quarter selector in the UI.
                     * Release always uses the latest ACTIVE quarter.
                     * Zero future quarters in All Quarters are ignored.
                     */
                    $releaseQuarter =
                        $this->latestActiveQuarter(
                            $storedQuarterStock,
                            $assignedQuarters
                        )
                        ?? '';

                    if ($releaseQuarter === '') {
                        throw ValidationException::withMessages([
                            'release_quantity' =>
                                'No active quarter is available for this item.',
                        ]);
                    }

                    /*
                     * Legacy single-quarter item:
                     * safely initialize its quarter from the old global balance.
                     *
                     * Legacy multi-quarter item:
                     * cannot be split accurately, so force one-time Edit setup.
                     */
                    if (empty($storedQuarterStock)) {
                        if (
                            count($assignedQuarters) !== 1
                        ) {
                            throw ValidationException::withMessages([
                                'release_quarter' =>
                                    'Set the remaining quantity for each quarter in Edit before releasing this legacy multi-quarter item.',
                            ]);
                        }

                        $onlyQuarter =
                            $assignedQuarters[0];

                        $legacyCurrent =
                            $oldCurrent ?? 0;

                        $legacyReleased =
                            max(
                                0,
                                (int) $oldDisplayedReleased
                            );

                        $storedQuarterStock = [
                            $onlyQuarter => [
                                'opening' =>
                                    $legacyCurrent
                                    + $legacyReleased,
                                'current' =>
                                    $legacyCurrent,
                                'released' =>
                                    $legacyReleased,
                            ],
                        ];
                    }

                    $quarterEntry =
                        $storedQuarterStock[
                            $releaseQuarter
                        ]
                        ?? null;

                    if (!$quarterEntry) {
                        throw ValidationException::withMessages([
                            'release_quarter' =>
                                'Set the balance for this quarter in Edit before releasing.',
                        ]);
                    }

                    $quarterCurrent =
                        (int) (
                            $quarterEntry['current']
                            ?? 0
                        );

                    if (
                        $releaseQuantity
                        > $quarterCurrent
                    ) {
                        throw ValidationException::withMessages([
                            'release_quantity' =>
                                "Only {$quarterCurrent} available in "
                                . strtoupper($releaseQuarter)
                                . '.',
                        ]);
                    }

                    $quarterReleased =
                        (int) (
                            $quarterEntry['released']
                            ?? 0
                        );

                    $quarterEntry['current'] =
                        $quarterCurrent
                        - $releaseQuantity;

                    $quarterEntry['released'] =
                        $quarterReleased
                        + $releaseQuantity;

                    $quarterEntry['opening'] =
                        (int) (
                            $quarterEntry['opening']
                            ?? (
                                $quarterCurrent
                                + $quarterReleased
                            )
                        );

                    $storedQuarterStock[
                        $releaseQuarter
                    ] =
                        $quarterEntry;

                    $item->quarter_stock =
                        $storedQuarterStock;

                    $item->currently_available =
                        $this->quarterStockCurrentTotal(
                            $storedQuarterStock
                        );

                    $hasFixedBaseline =
                        $category === 'supplies'
                        && $item->fixed_value !== null
                        && (int) $item->fixed_value > 0;

                    if (!$hasFixedBaseline) {
                        $item->tracked_released =
                            $this->quarterStockReleasedTotal(
                                $storedQuarterStock
                            );
                    }
                } else {
                    if ($oldCurrent === null) {
                        throw ValidationException::withMessages([
                            'release_quantity' =>
                                'Available quantity is not configured for this item.',
                        ]);
                    }

                    if (
                        $releaseQuantity
                        > $oldCurrent
                    ) {
                        throw ValidationException::withMessages([
                            'release_quantity' =>
                                "Only {$oldCurrent} available.",
                        ]);
                    }

                    $item->currently_available =
                        $oldCurrent
                        - $releaseQuantity;

                    $item->tracked_released =
                        $oldTrackedReleased
                        + $releaseQuantity;
                }
            }

            /**
             * ========================================================
             * OPTIONAL GENERAL UPDATES
             * ========================================================
             */
            if (array_key_exists('category', $validated)) {
                $item->category =
                    strtolower(trim($validated['category']));
            }

            if (array_key_exists('item', $validated)) {
                $item->item =
                    trim($validated['item']);
            }

            if (array_key_exists('location', $validated)) {
                $item->location =
                    $validated['location'] !== null
                        ? trim((string) $validated['location'])
                        : null;
            }

            if (array_key_exists('unit', $validated)) {
                $item->unit =
                    strtoupper(trim($validated['unit']));
            }

            if (array_key_exists('inventory_year', $validated)) {
                $item->inventory_year =
                    (int) $validated['inventory_year'];
            }

            if (array_key_exists('fixed_value', $validated)) {
                $item->fixed_value =
                    $validated['fixed_value'];
            }

            /*
             * Direct aggregate correction is legacy-only.
             * Quarter-aware Supplies/ICT use quarter_stock instead.
             */
            if (
                !array_key_exists(
                    'release_quantity',
                    $validated
                )
                &&
                array_key_exists(
                    'currently_available',
                    $validated
                )
                &&
                !array_key_exists(
                    'quarter_stock',
                    $validated
                )
            ) {
                $item->currently_available =
                    $validated['currently_available'];
            }

            if (array_key_exists('quarters', $validated)) {
                $item->quarters =
                    $this->normalizedQuarterList(
                        $validated['quarters']
                    );
            }

            if (
                !$isRelease
                && array_key_exists(
                    'quarter_stock',
                    $validated
                )
            ) {
                $targetCategory =
                    strtolower(
                        trim(
                            (string) (
                                $validated['category']
                                ?? $item->category
                            )
                        )
                    );

                if (
                    in_array(
                        $targetCategory,
                        ['supplies', 'ict'],
                        true
                    )
                ) {
                    $targetQuarters =
                        $this->normalizedQuarterList(
                            is_array($item->quarters)
                                ? $item->quarters
                                : []
                        );

                    $newQuarterStock =
                        $this->buildQuarterStock(
                            $targetQuarters,
                            $validated['quarter_stock'],
                            $item
                        );

                    $item->quarter_stock =
                        $newQuarterStock;

                    $item->currently_available =
                        $this->quarterStockCurrentTotal(
                            $newQuarterStock
                        );

                    $newHasFixedBaseline =
                        $targetCategory === 'supplies'
                        && $item->fixed_value !== null
                        && (int) $item->fixed_value > 0;

                    if (!$newHasFixedBaseline) {
                        $item->tracked_released =
                            $this->quarterStockReleasedTotal(
                                $newQuarterStock
                            );
                    }
                }
            }

            if (!$isRelease) {
                $newHasFixedBaseline =
                    $item->fixed_value !== null
                    && (int) $item->fixed_value > 0;

                if (
                    $oldHasFixedBaseline
                    && !$newHasFixedBaseline
                    && strtolower(trim((string) $item->category)) === 'supplies'
                ) {
                    $item->tracked_released = max(
                        (int) ($item->tracked_released ?? 0),
                        (int) $oldDisplayedReleased
                    );
                }
            }

            /*
             * Permanent item remarks may be edited by a normal item update.
             *
             * During a release, the remarks field is TRANSACTION-ONLY
             * and is written to Inventory History below.
             */
            if (
                !$isRelease
                && array_key_exists(
                    'remarks',
                    $validated
                )
            ) {
                $item->remarks =
                    $validated['remarks'];
            }

            $finalCategory =
                strtolower(
                    trim((string) $item->category)
                );

            $otherCategories = [
                'furniture',
                'fixtures',
                'emergency_kits',
                'token_giveaways',
            ];

            $finalIsOther =
                in_array(
                    $finalCategory,
                    $otherCategories,
                    true
                );

            /*
             * Other Items are location-based only.
             * Keep schema-compatibility values internally, but they are
             * intentionally hidden from the Other Items UI.
             */
            if ($finalIsOther) {
                $item->currently_available =
                    (int) ($item->currently_available ?? 0);

                $item->unit = 'N/A';
                $item->inventory_year =
                    $item->inventory_year
                    ?? max(2026, (int) now()->year);
                $item->quarters = [
                    'q1',
                    'q2',
                    'q3',
                    'q4',
                ];
                $item->quarter_stock = null;
                $item->fixed_value = null;

                $item->tracked_released =
                    (int) ($item->tracked_released ?? 0);
            } elseif ($finalCategory === 'ict') {
                $item->location = null;
                $item->fixed_value = null;
                $item->currently_available =
                    $item->currently_available !== null
                        ? (int) $item->currently_available
                        : 0;
                $item->tracked_released =
                    (int) ($item->tracked_released ?? 0);
            } else {
                $item->location = null;
            }

            $newCurrent =
                $item->currently_available !== null
                    ? (int) $item->currently_available
                    : null;

            $newRemarks =
                $item->remarks;

            $currentChanged =
                $oldCurrent !== $newCurrent;

            $remarksChanged =
                !$isRelease
                &&
                (
                    (string) ($oldRemarks ?? '')
                    !==
                    (string) ($newRemarks ?? '')
                );

            /*
             * For a release transaction, use a clean history-only
             * remark pair. This lets Vue show the release remark
             * without persisting it back into inventory_items.remarks.
             */
            $historyOldRemarks =
                $isRelease
                    ? null
                    : $oldRemarks;

            $historyNewRemarks =
                $isRelease
                    ? (
                        $releaseRemarks !== ''
                            ? $releaseRemarks
                            : null
                    )
                    : $newRemarks;

            $historyRemarksChanged =
                (string) (
                    $historyOldRemarks ?? ''
                )
                !==
                (string) (
                    $historyNewRemarks ?? ''
                );

            /*
             * Saving recalculates generated total_released in MySQL.
             */
            $item->save();
            $item->refresh();

            /*
             * Full audit snapshot AFTER save so generated/casted values are
             * normalized before comparing the record.
             */
            $historyNewData =
                $this->inventoryHistorySnapshot($item);

            /*
             * Release destination is transaction-only metadata.
             * Store it inside new_data JSON so no new history column
             * or migration is required.
             */
            if (
                $isRelease
                && $category !== 'supplies'
                && $releaseDestination !== ''
            ) {
                $historyNewData['release_destination'] =
                    $releaseDestination;
            }

            if (
                $isRelease
                && in_array(
                    $category,
                    ['supplies', 'ict'],
                    true
                )
            ) {
                $releaseHistoryQuarters =
                    $this->normalizedQuarterList(
                        is_array($item->quarters)
                            ? $item->quarters
                            : []
                    );

                if (!empty($releaseHistoryQuarters)) {
                    $historyReleaseQuarter =
                        $this->latestActiveQuarter(
                            is_array($item->quarter_stock)
                                ? $item->quarter_stock
                                : [],
                            $releaseHistoryQuarters
                        );

                    if ($historyReleaseQuarter) {
                        $historyNewData['release_quarter'] =
                            $historyReleaseQuarter;
                    }
                }
            }

            $fullRecordChanged =
                $historyOldData !== $historyNewData;

            /**
             * ========================================================
             * HISTORY
             * ========================================================
             *
             * History records the exact stock movement using old/new
             * Currently Available. This remains correct for both:
             * - fixed-baseline items
             * - system-tracked items
             */
            if (
                $fullRecordChanged
                || $currentChanged
                || $remarksChanged
                || $historyRemarksChanged
            ) {
                $history = new InventoryItemHistory();

                $history->inventory_item_id =
                    $item->id;

                $historyTable =
                    $history->getTable();

                /*
                 * New full-audit columns. Schema checks keep the controller
                 * backward-compatible while deploying the migration.
                 */
                if (
                    Schema::hasColumn(
                        $historyTable,
                        'action'
                    )
                ) {
                    $history->action =
                        $isRelease
                            ? 'release'
                            : 'edit';
                }

                if (
                    Schema::hasColumn(
                        $historyTable,
                        'old_data'
                    )
                ) {
                    $history->old_data =
                        $historyOldData;
                }

                if (
                    Schema::hasColumn(
                        $historyTable,
                        'new_data'
                    )
                ) {
                    $history->new_data =
                        $historyNewData;
                }

                if (
                    Schema::hasColumn(
                        $historyTable,
                        'old_currently_available'
                    )
                ) {
                    $history->old_currently_available =
                        $oldCurrent;
                } elseif (
                    Schema::hasColumn(
                        $historyTable,
                        'old_available'
                    )
                ) {
                    $history->old_available =
                        $oldCurrent;
                } elseif (
                    Schema::hasColumn(
                        $historyTable,
                        'legacy_old_available'
                    )
                ) {
                    $history->legacy_old_available =
                        $oldCurrent;
                }

                if (
                    Schema::hasColumn(
                        $historyTable,
                        'new_currently_available'
                    )
                ) {
                    $history->new_currently_available =
                        $newCurrent;
                } elseif (
                    Schema::hasColumn(
                        $historyTable,
                        'new_available'
                    )
                ) {
                    $history->new_available =
                        $newCurrent;
                } elseif (
                    Schema::hasColumn(
                        $historyTable,
                        'legacy_new_available'
                    )
                ) {
                    $history->legacy_new_available =
                        $newCurrent;
                }

                if (
                    Schema::hasColumn(
                        $historyTable,
                        'old_remarks'
                    )
                ) {
                    $history->old_remarks =
                        $historyOldRemarks;
                }

                if (
                    Schema::hasColumn(
                        $historyTable,
                        'new_remarks'
                    )
                ) {
                    $history->new_remarks =
                        $historyNewRemarks;
                }

                if (
                    Schema::hasColumn(
                        $historyTable,
                        'updated_by'
                    )
                ) {
                    $history->updated_by =
                        $userId;
                }

                if (
                    Schema::hasColumn(
                        $historyTable,
                        'updated_by_name'
                    )
                ) {
                    $history->updated_by_name =
                        $userName;
                }

                $history->save();
            }

            Log::info('Inventory item updated', [
                'inventory_item_id' =>
                    $item->id,

                'category' =>
                    $item->category,

                'fixed_value' =>
                    $item->fixed_value,

                'old_currently_available' =>
                    $oldCurrent,

                'new_currently_available' =>
                    $newCurrent,

                'total_released' =>
                    $item->total_released,

                'old_tracked_released' =>
                    $oldTrackedReleased,

                'new_tracked_released' =>
                    (int) ($item->tracked_released ?? 0),

                'release_remarks' =>
                    $releaseRemarks,

                'updated_by' =>
                    $userId,

                'updated_by_name' =>
                    $userName,
            ]);
        });

        return back()->with(
            'success',
            'Inventory item updated successfully.'
        );
    }

    /**
     * Inventory release/update history.
     */
    public function history(
        InventoryItem $inventoryItem
    ) {
        $histories = $inventoryItem
            ->histories()
            ->get()
            ->map(function ($history) {
                $oldData =
                    is_array($history->old_data ?? null)
                        ? $history->old_data
                        : [];

                $newData =
                    is_array($history->new_data ?? null)
                        ? $history->new_data
                        : [];

                $changes =
                    $this->inventoryHistoryChanges(
                        $oldData,
                        $newData
                    );

                $oldCurrent =
                    $history->old_currently_available
                    ?? $history->old_available
                    ?? $history->legacy_old_available
                    ?? null;

                $newCurrent =
                    $history->new_currently_available
                    ?? $history->new_available
                    ?? $history->legacy_new_available
                    ?? null;

                $action =
                    $history->action
                    ?? null;

                /*
                 * When a quarter is newly activated, show the exact
                 * quantity entered by the user instead of only showing
                 * the resulting aggregate Currently Available value.
                 *
                 * This does NOT restore the removed "Quarter Balances"
                 * history row.
                 */
                if ($action !== 'release') {
                    $oldQuarterStock =
                        is_array(
                            $oldData['quarter_stock']
                            ?? null
                        )
                            ? $oldData['quarter_stock']
                            : [];

                    $newQuarterStock =
                        is_array(
                            $newData['quarter_stock']
                            ?? null
                        )
                            ? $newData['quarter_stock']
                            : [];

                    foreach (
                        ['q1', 'q2', 'q3', 'q4']
                        as $quarter
                    ) {
                        $oldEntry =
                            is_array(
                                $oldQuarterStock[$quarter]
                                ?? null
                            )
                                ? $oldQuarterStock[$quarter]
                                : [];

                        $newEntry =
                            is_array(
                                $newQuarterStock[$quarter]
                                ?? null
                            )
                                ? $newQuarterStock[$quarter]
                                : [];

                        $oldAdded =
                            max(
                                0,
                                (int) (
                                    $oldEntry['added']
                                    ?? 0
                                )
                            );

                        $newAdded =
                            max(
                                0,
                                (int) (
                                    $newEntry['added']
                                    ?? 0
                                )
                            );

                        /*
                         * New quarter activation / newly added stock.
                         */
                        if ($newAdded > $oldAdded) {
                            $changes[] = [
                                'field' =>
                                    'quarter_quantity_added',

                                'label' =>
                                    'Quantity Added · '
                                    . strtoupper($quarter),

                                'old' =>
                                    null,

                                'new' =>
                                    $newAdded - $oldAdded,

                                'single' =>
                                    true,
                            ];
                        }
                    }
                }

                /*
                 * A release is an action rather than a directly editable
                 * field, so expose the exact released quantity as a
                 * synthetic history change.
                 */
                if (
                    $action === 'release'
                    && $oldCurrent !== null
                    && $newCurrent !== null
                    && (int) $oldCurrent > (int) $newCurrent
                ) {
                    $historyCategory =
                        strtolower(
                            trim(
                                (string) (
                                    $newData['category']
                                    ?? $oldData['category']
                                    ?? ''
                                )
                            )
                        );

                    $historyUnit =
                        strtoupper(
                            trim(
                                (string) (
                                    $newData['unit']
                                    ?? $oldData['unit']
                                    ?? ''
                                )
                            )
                        );

                    $releaseLabel =
                        $historyCategory === 'ict'
                            && $historyUnit === 'MONTH'
                                ? 'Month(s) Released'
                                : (
                                    $historyCategory === 'ict'
                                    && $historyUnit === 'YEAR'
                                        ? 'Year(s) Released'
                                        : 'Quantity Released'
                                );

                    array_unshift(
                        $changes,
                        [
                            'field' =>
                                'release_quantity',

                            'label' =>
                                $releaseLabel,

                            'old' =>
                                null,

                            'new' =>
                                (int) $oldCurrent
                                - (int) $newCurrent,

                            'single' =>
                                true,
                        ]
                    );
                }

                if (
                    $action === 'release'
                    && trim(
                        (string) (
                            $newData['release_destination']
                            ?? ''
                        )
                    ) !== ''
                ) {
                    $changes[] = [
                        'field' =>
                            'release_destination',

                        'label' =>
                            'Released To / Destination',

                        'old' =>
                            null,

                        'new' =>
                            $newData['release_destination'],

                        'single' =>
                            true,
                    ];
                }

                /*
                 * Release remarks are transaction-only and do not modify the
                 * permanent inventory_items.remarks field, so add them to
                 * the detailed changes explicitly.
                 */
                if (
                    $action === 'release'
                    && trim(
                        (string) (
                            $history->new_remarks
                            ?? ''
                        )
                    ) !== ''
                ) {
                    $changes[] = [
                        'field' =>
                            'remarks',

                        'label' =>
                            'Remarks',

                        'old' =>
                            null,

                        'new' =>
                            $history->new_remarks,

                        'single' =>
                            true,
                    ];
                }

                return [
                    'id' =>
                        $history->id,

                    'action' =>
                        $action,

                    'changes' =>
                        $changes,

                    'old_data' =>
                        $oldData,

                    'new_data' =>
                        $newData,

                    'old_currently_available' =>
                        $oldCurrent,

                    'new_currently_available' =>
                        $newCurrent,

                    /* Compatibility aliases for current Vue helpers. */
                    'old_available' =>
                        $oldCurrent,

                    'new_available' =>
                        $newCurrent,

                    'old_remarks' =>
                        $history->old_remarks,

                    'new_remarks' =>
                        $history->new_remarks,

                    'updated_by' =>
                        $history->updated_by,

                    'updated_by_name' =>
                        $history->updated_by_name,

                    'created_at' =>
                        $history->created_at
                            ?->timezone('Asia/Manila')
                            ->format('M d, Y h:i A'),
                ];
            });

        $inventoryItem->refresh();

        return response()->json([
            'item' => [
                'id' =>
                    $inventoryItem->id,

                'category' =>
                    strtolower(
                        trim((string) $inventoryItem->category)
                    ),

                'item' =>
                    $inventoryItem->item,

                'unit' =>
                    $inventoryItem->unit,

                'fixed_value' =>
                    $inventoryItem->fixed_value,

                'currently_available' =>
                    $inventoryItem->currently_available,

                /* Generated when Fixed Value > 0. */
                'total_released' =>
                    $inventoryItem->total_released,

                /* Used when there is no usable Fixed Value. */
                'tracked_released' =>
                    (int) ($inventoryItem->tracked_released ?? 0),

                'remarks' =>
                    $inventoryItem->remarks,
            ],

            'histories' =>
                $histories,
        ]);
    }

    /**
     * Return only user-visible/editable inventory values for audit history.
     *
     * Internal/generated fields are deliberately excluded so History stays
     * understandable to users and does not show implementation noise.
     */
    private function inventoryHistorySnapshot(
        InventoryItem $item
    ): array {
        $quarters =
            is_array($item->quarters)
                ? $item->quarters
                : [];

        $quarterOrder = [
            'q1' => 1,
            'q2' => 2,
            'q3' => 3,
            'q4' => 4,
        ];

        $quarters = array_values(
            array_unique(
                array_filter(
                    array_map(
                        fn ($quarter) =>
                            strtolower(
                                trim((string) $quarter)
                            ),
                        $quarters
                    ),
                    fn ($quarter) =>
                        array_key_exists(
                            $quarter,
                            $quarterOrder
                        )
                )
            )
        );

        usort(
            $quarters,
            fn ($a, $b) =>
                $quarterOrder[$a]
                <=>
                $quarterOrder[$b]
        );

        $category =
            strtolower(
                trim((string) $item->category)
            );

        $isOtherItem =
            in_array(
                $category,
                [
                    'furniture',
                    'fixtures',
                    'emergency_kits',
                    'token_giveaways',
                ],
                true
            );

        return [
            'category' =>
                $category,

            'item' =>
                trim((string) $item->item),

            'location' =>
                $isOtherItem
                    ? (
                        $item->location !== null
                            ? trim((string) $item->location)
                            : null
                    )
                    : null,

            'unit' =>
                $isOtherItem
                    ? null
                    : strtoupper(
                        trim((string) $item->unit)
                    ),

            'inventory_year' =>
                $isOtherItem
                    ? null
                    : (
                        $item->inventory_year !== null
                            ? (int) $item->inventory_year
                            : null
                    ),

            'quarters' =>
                $isOtherItem
                    ? []
                    : $quarters,

            'quarter_stock' =>
                $isOtherItem
                    ? []
                    : $this->normalizedStoredQuarterStock(
                        $item->quarter_stock
                    ),

            'fixed_value' =>
                $item->fixed_value !== null
                    ? (int) $item->fixed_value
                    : null,

            'currently_available' =>
                $item->currently_available !== null
                    ? (int) $item->currently_available
                    : null,

            'remarks' =>
                $item->remarks !== null
                    ? (string) $item->remarks
                    : null,
        ];
    }

    /**
     * Convert old/new audit snapshots into a clean list of changed fields.
     */
    private function inventoryHistoryChanges(
        array $oldData,
        array $newData
    ): array {
        if (
            empty($oldData)
            || empty($newData)
        ) {
            return [];
        }

        $historyCategory =
            strtolower(
                trim(
                    (string) (
                        $newData['category']
                        ?? $oldData['category']
                        ?? ''
                    )
                )
            );

        $countedOtherCategories = [
            'furniture',
            'fixtures',
            'emergency_kits',
            'token_giveaways',
        ];

        $historyUnit =
            strtoupper(
                trim(
                    (string) (
                        $newData['unit']
                        ?? $oldData['unit']
                        ?? ''
                    )
                )
            );

        if ($historyCategory === 'ict') {
            if ($historyUnit === 'MONTH') {
                $currentAvailableLabel =
                    'Month(s)';
            } elseif ($historyUnit === 'YEAR') {
                $currentAvailableLabel =
                    'Year(s)';
            } else {
                $currentAvailableLabel =
                    'Count';
            }
        } else {
            $currentAvailableLabel =
                in_array(
                    $historyCategory,
                    $countedOtherCategories,
                    true
                )
                    ? 'Count'
                    : 'Currently Available in SPD';
        }

        $fields = [
            'category' => 'Category',
            'item' => 'Item Name',
            'location' => 'Location',
            'unit' => 'Unit',
            'inventory_year' => 'Inventory Year',
            'quarters' => 'Quarter(s)',
            'fixed_value' => 'Fixed Value',
            'currently_available' =>
                $currentAvailableLabel,
            'remarks' => 'Remarks',
        ];

        $changes = [];

        foreach ($fields as $field => $label) {
            $oldValue =
                $oldData[$field]
                ?? null;

            $newValue =
                $newData[$field]
                ?? null;

            if ($oldValue === $newValue) {
                continue;
            }

            $changes[] = [
                'field' =>
                    $field,

                'label' =>
                    $label,

                'old' =>
                    $oldValue,

                'new' =>
                    $newValue,

                'single' =>
                    false,
            ];
        }

        return $changes;
    }

    /**
     * Normalize assigned quarter names.
     */
    private function normalizedQuarterList(
        mixed $quarters
    ): array {
        $allowed = [
            'q1',
            'q2',
            'q3',
            'q4',
        ];

        if (!is_array($quarters)) {
            return [];
        }

        $normalized =
            array_values(
                array_unique(
                    array_filter(
                        array_map(
                            fn ($quarter) =>
                                strtolower(
                                    trim(
                                        (string) $quarter
                                    )
                                ),
                            $quarters
                        ),
                        fn ($quarter) =>
                            in_array(
                                $quarter,
                                $allowed,
                                true
                            )
                    )
                )
            );

        usort(
            $normalized,
            fn ($a, $b) =>
                array_search(
                    $a,
                    $allowed,
                    true
                )
                <=>
                array_search(
                    $b,
                    $allowed,
                    true
                )
        );

        return $normalized;
    }

    private function quarterStockEntryHasActivity(
        array $entry
    ): bool {
        foreach (
            [
                'opening',
                'carryover',
                'added',
                'current',
                'released',
            ]
            as $field
        ) {
            if (
                (int) (
                    $entry[$field]
                    ?? 0
                ) > 0
            ) {
                return true;
            }
        }

        return false;
    }

    /**
     * Return the latest quarter that has actual stock activity.
     * Completely zero future quarters are dormant.
     */
    private function latestActiveQuarter(
        array $quarterStock,
        array $assignedQuarters = []
    ): ?string {
        $normalized =
            $this->normalizedStoredQuarterStock(
                $quarterStock
            );

        $latest = null;

        foreach (
            ['q1', 'q2', 'q3', 'q4']
            as $quarter
        ) {
            if (
                isset($normalized[$quarter])
                && $this->quarterStockEntryHasActivity(
                    $normalized[$quarter]
                )
            ) {
                $latest = $quarter;
            }
        }

        if ($latest !== null) {
            return $latest;
        }

        $assigned =
            $this->normalizedQuarterList(
                $assignedQuarters
            );

        return !empty($assigned)
            ? $assigned[0]
            : null;
    }

    /**
     * Clean a stored quarter_stock JSON value.
     */
    private function normalizedStoredQuarterStock(
        mixed $quarterStock
    ): array {
        if (!is_array($quarterStock)) {
            return [];
        }

        $normalized = [];

        foreach (
            ['q1', 'q2', 'q3', 'q4']
            as $quarter
        ) {
            $entry =
                $quarterStock[$quarter]
                ?? null;

            if (!is_array($entry)) {
                continue;
            }

            if (
                !array_key_exists(
                    'current',
                    $entry
                )
            ) {
                continue;
            }

            $current =
                max(
                    0,
                    (int) $entry['current']
                );

            $released =
                max(
                    0,
                    (int) (
                        $entry['released']
                        ?? 0
                    )
                );

            $opening =
                max(
                    0,
                    (int) (
                        $entry['opening']
                        ?? (
                            $current
                            + $released
                        )
                    )
                );

            $carryover =
                max(
                    0,
                    (int) (
                        $entry['carryover']
                        ?? 0
                    )
                );

            $added =
                max(
                    0,
                    (int) (
                        $entry['added']
                        ?? max(
                            0,
                            $opening
                            - $carryover
                        )
                    )
                );

            $normalized[$quarter] = [
                'opening' =>
                    $opening,

                'carryover' =>
                    $carryover,

                'added' =>
                    $added,

                'current' =>
                    $current,

                'released' =>
                    $released,
            ];
        }

        /*
         * Repair the carryover chain for ACTIVE quarters only.
         * Completely zero entries are future/dormant quarters and
         * must not automatically become active just because the item
         * is assigned to All Quarters.
         */
        $previousCurrent = 0;
        $hasPreviousActive = false;

        foreach (
            ['q1', 'q2', 'q3', 'q4']
            as $quarter
        ) {
            if (!isset($normalized[$quarter])) {
                continue;
            }

            $entry =
                $normalized[$quarter];

            if (
                !$this->quarterStockEntryHasActivity(
                    $entry
                )
            ) {
                $normalized[$quarter] = [
                    'opening' => 0,
                    'carryover' => 0,
                    'added' => 0,
                    'current' => 0,
                    'released' => 0,
                ];

                continue;
            }

            $released =
                max(
                    0,
                    (int) (
                        $entry['released']
                        ?? 0
                    )
                );

            $storedCarryover =
                max(
                    0,
                    (int) (
                        $entry['carryover']
                        ?? 0
                    )
                );

            $storedOpening =
                max(
                    0,
                    (int) (
                        $entry['opening']
                        ?? 0
                    )
                );

            $added =
                max(
                    0,
                    (int) (
                        $entry['added']
                        ?? max(
                            0,
                            $storedOpening
                            - $storedCarryover
                        )
                    )
                );

            $carryover =
                $hasPreviousActive
                    ? $previousCurrent
                    : 0;

            $opening =
                $carryover
                + $added;

            $current =
                max(
                    0,
                    $opening
                    - $released
                );

            $normalized[$quarter] = [
                'opening' =>
                    $opening,

                'carryover' =>
                    $carryover,

                'added' =>
                    $added,

                'current' =>
                    $current,

                'released' =>
                    $released,
            ];

            $previousCurrent =
                $current;

            $hasPreviousActive =
                true;
        }

        return $normalized;
    }

    /**
     * Build quarter balances for Add/Edit.
     */
    private function buildQuarterStock(
        array $quarters,
        mixed $rawQuarterStock,
        ?InventoryItem $item = null
    ): array {
        $raw =
            is_array($rawQuarterStock)
                ? $rawQuarterStock
                : [];

        $existing =
            $item
                ? $this->normalizedStoredQuarterStock(
                    $item->quarter_stock
                )
                : [];

        $legacyReleased = 0;

        if (
            $item
            && empty($existing)
            && count($quarters) === 1
        ) {
            $legacyCurrent =
                $item->currently_available !== null
                    ? (int) $item->currently_available
                    : 0;

            $hasFixedBaseline =
                $item->fixed_value !== null
                && (int) $item->fixed_value > 0;

            $legacyReleased =
                $hasFixedBaseline
                    ? max(
                        0,
                        (int) $item->fixed_value
                        - $legacyCurrent
                    )
                    : max(
                        0,
                        (int) (
                            $item->tracked_released
                            ?? 0
                        )
                    );
        }

        $result = [];
        $previousCurrent = 0;

        foreach ($quarters as $quarter) {
            $rawEntry =
                $raw[$quarter]
                ?? [];

            if (
                !is_array($rawEntry)
                || !array_key_exists(
                    'current',
                    $rawEntry
                )
            ) {
                throw ValidationException::withMessages([
                    "quarter_stock.{$quarter}.current" =>
                        'Enter the quantity for '
                        . strtoupper($quarter)
                        . '.',
                ]);
            }

            $rawValue =
                (int) $rawEntry['current'];

            if ($rawValue < 0) {
                throw ValidationException::withMessages([
                    "quarter_stock.{$quarter}.current" =>
                        'Quarter quantity cannot be negative.',
                ]);
            }

            $existingEntry =
                $existing[$quarter]
                ?? null;

            $existingStarted =
                is_array($existingEntry)
                && $this->quarterStockEntryHasActivity(
                    $existingEntry
                );

            $activateRequested =
                filter_var(
                    $rawEntry['activate']
                    ?? false,
                    FILTER_VALIDATE_BOOLEAN
                );

            /*
             * EXISTING ACTIVE QUARTER:
             * rawValue is a remaining-balance correction.
             */
            if ($existingStarted) {
                $released =
                    max(
                        0,
                        (int) (
                            $existingEntry[
                                'released'
                            ]
                            ?? 0
                        )
                    );

                $carryover =
                    max(
                        0,
                        (int) (
                            $existingEntry[
                                'carryover'
                            ]
                            ?? 0
                        )
                    );

                $opening =
                    $rawValue
                    + $released;

                $added =
                    max(
                        0,
                        $opening
                        - $carryover
                    );

                $result[$quarter] = [
                    'opening' =>
                        $opening,

                    'carryover' =>
                        $carryover,

                    'added' =>
                        $added,

                    'current' =>
                        $rawValue,

                    'released' =>
                        $released,
                ];

                $previousCurrent =
                    $rawValue;

                continue;
            }

            /*
             * EXISTING DORMANT FUTURE QUARTER:
             * Keep it zero until the user actually enters/activates it.
             *
             * Entering a positive new quantity automatically activates
             * it. The frontend also sends activate=true when the user
             * edits/toggles a dormant quarter, including a zero-addition
             * carryover-only activation.
             */
            if (
                is_array($existingEntry)
                && !$activateRequested
                && $rawValue === 0
            ) {
                $result[$quarter] = [
                    'opening' => 0,
                    'carryover' => 0,
                    'added' => 0,
                    'current' => 0,
                    'released' => 0,
                ];

                /*
                 * Do NOT change previousCurrent. The next activated
                 * quarter still carries from the latest active quarter.
                 */
                continue;
            }

            /*
             * LEGACY SINGLE QUARTER:
             * rawValue is still the old remaining balance.
             */
            if (
                $item
                && empty($existing)
                && count($quarters) === 1
            ) {
                $opening =
                    $rawValue
                    + $legacyReleased;

                $result[$quarter] = [
                    'opening' =>
                        $opening,

                    'carryover' =>
                        0,

                    'added' =>
                        $opening,

                    'current' =>
                        $rawValue,

                    'released' =>
                        $legacyReleased,
                ];

                $previousCurrent =
                    $rawValue;

                continue;
            }

            /*
             * NEW QUARTER:
             * rawValue is NEW stock for this quarter.
             * Previous quarter remaining is automatically carried
             * forward and is NOT deducted from the historical quarter.
             *
             * Example:
             * Q1 remaining = 10
             * Q2 new stock = 25
             * Q2 opening/current = 35
             * Q1 historical remaining stays 10.
             */
            $carryover =
                max(
                    0,
                    (int) $previousCurrent
                );

            $added =
                $rawValue;

            $opening =
                $carryover
                + $added;

            $result[$quarter] = [
                'opening' =>
                    $opening,

                'carryover' =>
                    $carryover,

                'added' =>
                    $added,

                'current' =>
                    $opening,

                'released' =>
                    0,
            ];

            $previousCurrent =
                $opening;
        }

        return $result;
    }

    private function quarterStockCurrentTotal(
        array $quarterStock
    ): int {
        $normalized =
            $this->normalizedStoredQuarterStock(
                $quarterStock
            );

        $latestQuarter =
            $this->latestActiveQuarter(
                $normalized
            );

        if ($latestQuarter === null) {
            return 0;
        }

        return max(
            0,
            (int) (
                $normalized[
                    $latestQuarter
                ]['current']
                ?? 0
            )
        );
    }

    private function quarterStockReleasedTotal(
        array $quarterStock
    ): int {
        return array_sum(
            array_map(
                fn ($entry) =>
                    max(
                        0,
                        (int) (
                            $entry['released']
                            ?? 0
                        )
                    ),
                $quarterStock
            )
        );
    }

    /**
     * Role 3 is the only role that can manage Inventory.
     *
     * DTS primarily stores the role in "rights". Fallbacks are included for
     * accounts exposing role/role_number.
     */
    private function canManageInventory(
        $user
    ): bool {
        if (!$user) {
            return false;
        }

        $role =
            $user->rights
            ?? $user->role
            ?? $user->role_number
            ?? null;

        return trim(
            (string) $role
        ) === '3';
    }

    /**
     * The backend is the actual security boundary.
     * Non-role-3 users receive HTTP 403 on Inventory writes.
     */
    private function authorizeInventoryManagement(
        Request $request
    ): void {
        abort_unless(
            $this->canManageInventory(
                $request->user()
            ),
            403,
            'You have view-only access to the Inventory module.'
        );
    }

    public function destroy(
        Request $request,
        InventoryItem $inventoryItem
    ) {
        $this->authorizeInventoryManagement(
            $request
        );

       
        $inventoryItem->histories()->delete();
        $inventoryItem->delete();

        return back()->with(
            'success',
            'Inventory item deleted successfully.'
        );
    }
}
