<?php

namespace App\Http\Controllers;

use App\Models\InventoryItem;
use App\Models\InventoryItemHistory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Schema;
use Illuminate\Validation\ValidationException;
use Inertia\Inertia;

class InventoryController extends Controller
{
    /**
     * Inventory page.
     */
    public function index()
    {
        return Inertia::render('DTS/Inventory', [
            'inventoryItems' => InventoryItem::query()
                ->orderByRaw("
                    CASE
                        WHEN LOWER(TRIM(category)) = 'supplies' THEN 1
                        WHEN LOWER(TRIM(category)) = 'ict' THEN 2
                        ELSE 3
                    END
                ")
                ->orderBy('item')
                ->get(),
        ]);
    }

    /**
     * Add a new Supplies or ICT & Other Items record.
     *
     * SUPPLIES
     * - Fixed Value is optional.
     * - Currently Available is required.
     * - If Fixed Value exists (> 0):
     *      Quantity Released = Fixed - Current (generated by MySQL)
     * - If Fixed Value is missing / 0:
     *      tracked_released starts at 0 and future releases accumulate there.
     *
     * ICT & OTHER ITEMS
     * - Item, Unit, Inventory Year, Quarter(s), Remarks.
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'category' => 'required|in:supplies,ict',
            'item' => 'required|string|max:255',
            'unit' => 'required|string|max:50',
            'inventory_year' => 'required|integer|min:2026|max:2100',
            'fixed_value' => 'nullable|integer|min:0',
            'currently_available' =>
                'required_if:category,supplies|nullable|integer|min:0',
            'quarters' =>
                'required|array|min:1',
            'quarters.*' => 'in:q1,q2,q3,q4',
            'remarks' => 'nullable|string',
        ]);

        $validated['category'] =
            strtolower(trim($validated['category']));

        $validated['unit'] =
            strtoupper(trim($validated['unit']));

        /*
         * ICT & Other Items do not use the stock/release workflow,
         * but they still belong to an Inventory Year + Quarter(s).
         */
        if ($validated['category'] === 'ict') {
            $validated['fixed_value'] = null;
            $validated['currently_available'] = null;
        }

        /*
         * Never send total_released or tracked_released from the form.
         * - total_released is generated by MySQL.
         * - tracked_released starts at DB default 0.
         */
        InventoryItem::create($validated);

        return back()->with(
            'success',
            'Inventory item added successfully.'
        );
    }

    /**
     * Update / release an inventory item.
     */
    public function update(
        Request $request,
        InventoryItem $inventoryItem
    ) {
        $validated = $request->validate([
            'release_quantity' =>
                'sometimes|required|integer|min:1',

            'category' =>
                'sometimes|required|in:supplies,ict',

            'item' =>
                'sometimes|required|string|max:255',

            'unit' =>
                'sometimes|required|string|max:50',

            'inventory_year' =>
                'sometimes|required|integer|min:2026|max:2100',

            'fixed_value' =>
                'sometimes|nullable|integer|min:0',

            'currently_available' =>
                'sometimes|nullable|integer|min:0',

            'quarters' =>
                'sometimes|required|array|min:1',

            'quarters.*' =>
                'in:q1,q2,q3,q4',

            'remarks' =>
                'sometimes|nullable|string',
        ]);

        $user = $request->user();

        $userId = $user?->getKey();

        $userName =
            $user?->name
            ?? $user?->loginname
            ?? $user?->username
            ?? $user?->email
            ?? 'Unknown User';

        DB::transaction(function () use (
            $inventoryItem,
            $validated,
            $userId,
            $userName
        ) {
            /*
             * Lock the row so simultaneous releases cannot overdraw stock.
             */
            $item = InventoryItem::query()
                ->whereKey($inventoryItem->id)
                ->lockForUpdate()
                ->firstOrFail();

            $category =
                strtolower(trim((string) $item->category));

            $oldCurrent =
                $item->currently_available !== null
                    ? (int) $item->currently_available
                    : null;

            $oldTrackedReleased =
                (int) ($item->tracked_released ?? 0);

            $oldHasFixedBaseline =
                $item->fixed_value !== null
                && (int) $item->fixed_value > 0;

            $oldDisplayedReleased =
                $oldHasFixedBaseline
                    && $oldCurrent !== null
                        ? max(
                            0,
                            (int) $item->fixed_value
                            - $oldCurrent
                        )
                        : $oldTrackedReleased;

            $oldRemarks =
                $item->remarks;

            $isRelease =
                array_key_exists(
                    'release_quantity',
                    $validated
                );

            /*
             * A remark entered in the Release modal belongs to
             * that release transaction. It must not become the
             * permanent item remark or reappear next time.
             */
            $releaseRemarks =
                $isRelease
                    ? trim(
                        (string) (
                            $validated['remarks']
                            ?? ''
                        )
                    )
                    : '';

            if (!$isRelease) {
                $targetCategory = strtolower(
                    trim((string) ($validated['category'] ?? $item->category))
                );

                $targetItemName = trim(
                    (string) ($validated['item'] ?? $item->item)
                );

                $targetUnit = strtoupper(
                    trim((string) ($validated['unit'] ?? $item->unit))
                );

                $targetYear = (int) (
                    $validated['inventory_year']
                    ?? $item->inventory_year
                    ?? 2026
                );

                if (
                    $targetCategory === 'supplies'
                    && (
                        !array_key_exists('currently_available', $validated)
                        || $validated['currently_available'] === null
                    )
                ) {
                    throw ValidationException::withMessages([
                        'currently_available' =>
                            'Currently Available is required for Supplies.',
                    ]);
                }

                $duplicateExists = InventoryItem::query()
                    ->where('id', '!=', $item->id)
                    ->whereRaw(
                        'LOWER(TRIM(category)) = ?',
                        [$targetCategory]
                    )
                    ->whereRaw(
                        'LOWER(TRIM(item)) = ?',
                        [strtolower($targetItemName)]
                    )
                    ->whereRaw(
                        'UPPER(TRIM(unit)) = ?',
                        [$targetUnit]
                    )
                    ->where('inventory_year', $targetYear)
                    ->exists();

                if ($duplicateExists) {
                    throw ValidationException::withMessages([
                        'item' =>
                            "This item and unit already exist for {$targetYear}.",
                    ]);
                }
            }

            /**
             * ========================================================
             * RELEASE SUPPLY
             * ========================================================
             */
            if (
                array_key_exists(
                    'release_quantity',
                    $validated
                )
            ) {
                if ($category !== 'supplies') {
                    throw ValidationException::withMessages([
                        'release_quantity' =>
                            'Release tracking applies to Supplies only.',
                    ]);
                }

                if ($oldCurrent === null) {
                    throw ValidationException::withMessages([
                        'release_quantity' =>
                            'Currently Available is not configured for this item.',
                    ]);
                }

                $releaseQuantity =
                    (int) $validated['release_quantity'];

                if ($releaseQuantity > $oldCurrent) {
                    throw ValidationException::withMessages([
                        'release_quantity' =>
                            "Only {$oldCurrent} item(s) are currently available.",
                    ]);
                }

                $item->currently_available =
                    $oldCurrent - $releaseQuantity;

                /*
                 * HYBRID QUANTITY RELEASED LOGIC
                 *
                 * A usable Fixed Value means a positive baseline.
                 * Example: Fixed 30, Current 11 => Released 19.
                 * MySQL generates total_released automatically.
                 *
                 * If Fixed Value is NULL / blank / 0, there is no usable
                 * historical baseline. In that case, every release made
                 * through the system is accumulated in tracked_released.
                 *
                 * Example:
                 *   Current 4, tracked 0
                 *   release 2 => Current 2, tracked 2
                 *   release 1 => Current 1, tracked 3
                 */
                $hasFixedBaseline =
                    $item->fixed_value !== null
                    && (int) $item->fixed_value > 0;

                if (!$hasFixedBaseline) {
                    $item->tracked_released =
                        $oldTrackedReleased
                        + $releaseQuantity;
                }
            }

            /**
             * ========================================================
             * OPTIONAL GENERAL UPDATES
             * ========================================================
             */
            if (array_key_exists('category', $validated)) {
                $item->category =
                    strtolower(trim($validated['category']));
            }

            if (array_key_exists('item', $validated)) {
                $item->item =
                    trim($validated['item']);
            }

            if (array_key_exists('unit', $validated)) {
                $item->unit =
                    strtoupper(trim($validated['unit']));
            }

            if (array_key_exists('inventory_year', $validated)) {
                $item->inventory_year =
                    (int) $validated['inventory_year'];
            }

            if (array_key_exists('fixed_value', $validated)) {
                $item->fixed_value =
                    $validated['fixed_value'];
            }

            /*
             * Direct stock correction is allowed only when this is not
             * a release request. It does NOT change tracked_released.
             */
            if (
                !array_key_exists(
                    'release_quantity',
                    $validated
                )
                &&
                array_key_exists(
                    'currently_available',
                    $validated
                )
            ) {
                $item->currently_available =
                    $validated['currently_available'];
            }

            if (array_key_exists('quarters', $validated)) {
                $item->quarters =
                    $validated['quarters'];
            }

            if (!$isRelease) {
                $newHasFixedBaseline =
                    $item->fixed_value !== null
                    && (int) $item->fixed_value > 0;

                if (
                    $oldHasFixedBaseline
                    && !$newHasFixedBaseline
                    && strtolower(trim((string) $item->category)) === 'supplies'
                ) {
                    $item->tracked_released = max(
                        (int) ($item->tracked_released ?? 0),
                        (int) $oldDisplayedReleased
                    );
                }
            }

            /*
             * Permanent item remarks may be edited by a normal item update.
             *
             * During a release, the remarks field is TRANSACTION-ONLY
             * and is written to Inventory History below.
             */
            if (
                !$isRelease
                && array_key_exists(
                    'remarks',
                    $validated
                )
            ) {
                $item->remarks =
                    $validated['remarks'];
            }

            /*
             * ICT does not use stock/release fields.
             */
            if (
                strtolower(trim((string) $item->category))
                === 'ict'
            ) {
                $item->fixed_value = null;
                $item->currently_available = null;
                $item->tracked_released = 0;
            }

            $newCurrent =
                $item->currently_available !== null
                    ? (int) $item->currently_available
                    : null;

            $newRemarks =
                $item->remarks;

            $currentChanged =
                $oldCurrent !== $newCurrent;

            $remarksChanged =
                !$isRelease
                &&
                (
                    (string) ($oldRemarks ?? '')
                    !==
                    (string) ($newRemarks ?? '')
                );

            /*
             * For a release transaction, use a clean history-only
             * remark pair. This lets Vue show the release remark
             * without persisting it back into inventory_items.remarks.
             */
            $historyOldRemarks =
                $isRelease
                    ? null
                    : $oldRemarks;

            $historyNewRemarks =
                $isRelease
                    ? (
                        $releaseRemarks !== ''
                            ? $releaseRemarks
                            : null
                    )
                    : $newRemarks;

            $historyRemarksChanged =
                (string) (
                    $historyOldRemarks ?? ''
                )
                !==
                (string) (
                    $historyNewRemarks ?? ''
                );

            /*
             * Saving recalculates generated total_released in MySQL.
             */
            $item->save();
            $item->refresh();

            /**
             * ========================================================
             * HISTORY
             * ========================================================
             *
             * History records the exact stock movement using old/new
             * Currently Available. This remains correct for both:
             * - fixed-baseline items
             * - system-tracked items
             */
            if (
                $currentChanged
                || $remarksChanged
                || $historyRemarksChanged
            ) {
                $history = new InventoryItemHistory();

                $history->inventory_item_id =
                    $item->id;

                $historyTable =
                    $history->getTable();

                if (
                    Schema::hasColumn(
                        $historyTable,
                        'old_currently_available'
                    )
                ) {
                    $history->old_currently_available =
                        $oldCurrent;
                } elseif (
                    Schema::hasColumn(
                        $historyTable,
                        'old_available'
                    )
                ) {
                    $history->old_available =
                        $oldCurrent;
                } elseif (
                    Schema::hasColumn(
                        $historyTable,
                        'legacy_old_available'
                    )
                ) {
                    $history->legacy_old_available =
                        $oldCurrent;
                }

                if (
                    Schema::hasColumn(
                        $historyTable,
                        'new_currently_available'
                    )
                ) {
                    $history->new_currently_available =
                        $newCurrent;
                } elseif (
                    Schema::hasColumn(
                        $historyTable,
                        'new_available'
                    )
                ) {
                    $history->new_available =
                        $newCurrent;
                } elseif (
                    Schema::hasColumn(
                        $historyTable,
                        'legacy_new_available'
                    )
                ) {
                    $history->legacy_new_available =
                        $newCurrent;
                }

                if (
                    Schema::hasColumn(
                        $historyTable,
                        'old_remarks'
                    )
                ) {
                    $history->old_remarks =
                        $historyOldRemarks;
                }

                if (
                    Schema::hasColumn(
                        $historyTable,
                        'new_remarks'
                    )
                ) {
                    $history->new_remarks =
                        $historyNewRemarks;
                }

                if (
                    Schema::hasColumn(
                        $historyTable,
                        'updated_by'
                    )
                ) {
                    $history->updated_by =
                        $userId;
                }

                if (
                    Schema::hasColumn(
                        $historyTable,
                        'updated_by_name'
                    )
                ) {
                    $history->updated_by_name =
                        $userName;
                }

                $history->save();
            }

            Log::info('Inventory item updated', [
                'inventory_item_id' =>
                    $item->id,

                'category' =>
                    $item->category,

                'fixed_value' =>
                    $item->fixed_value,

                'old_currently_available' =>
                    $oldCurrent,

                'new_currently_available' =>
                    $newCurrent,

                'total_released' =>
                    $item->total_released,

                'old_tracked_released' =>
                    $oldTrackedReleased,

                'new_tracked_released' =>
                    (int) ($item->tracked_released ?? 0),

                'release_remarks' =>
                    $releaseRemarks,

                'updated_by' =>
                    $userId,

                'updated_by_name' =>
                    $userName,
            ]);
        });

        return back()->with(
            'success',
            'Inventory item updated successfully.'
        );
    }

    /**
     * Inventory release/update history.
     */
    public function history(
        InventoryItem $inventoryItem
    ) {
        $histories = $inventoryItem
            ->histories()
            ->get()
            ->map(function ($history) {
                $oldCurrent =
                    $history->old_currently_available
                    ?? $history->old_available
                    ?? $history->legacy_old_available
                    ?? null;

                $newCurrent =
                    $history->new_currently_available
                    ?? $history->new_available
                    ?? $history->legacy_new_available
                    ?? null;

                return [
                    'id' =>
                        $history->id,

                    'old_currently_available' =>
                        $oldCurrent,

                    'new_currently_available' =>
                        $newCurrent,

                    /* Compatibility aliases for current Vue helpers. */
                    'old_available' =>
                        $oldCurrent,

                    'new_available' =>
                        $newCurrent,

                    'old_remarks' =>
                        $history->old_remarks,

                    'new_remarks' =>
                        $history->new_remarks,

                    'updated_by' =>
                        $history->updated_by,

                    'updated_by_name' =>
                        $history->updated_by_name,

                    'created_at' =>
                        $history->created_at
                            ?->timezone('Asia/Manila')
                            ->format('M d, Y h:i A'),
                ];
            });

        $inventoryItem->refresh();

        return response()->json([
            'item' => [
                'id' =>
                    $inventoryItem->id,

                'category' =>
                    strtolower(
                        trim((string) $inventoryItem->category)
                    ),

                'item' =>
                    $inventoryItem->item,

                'unit' =>
                    $inventoryItem->unit,

                'fixed_value' =>
                    $inventoryItem->fixed_value,

                'currently_available' =>
                    $inventoryItem->currently_available,

                /* Generated when Fixed Value > 0. */
                'total_released' =>
                    $inventoryItem->total_released,

                /* Used when there is no usable Fixed Value. */
                'tracked_released' =>
                    (int) ($inventoryItem->tracked_released ?? 0),

                'remarks' =>
                    $inventoryItem->remarks,
            ],

            'histories' =>
                $histories,
        ]);
    }

    public function destroy(
        InventoryItem $inventoryItem
    ) {
        $inventoryItem->delete();

        return back()->with(
            'success',
            'Inventory item deleted successfully.'
        );
    }
}
