<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class InventoryItem extends Model
{
    protected $fillable = [
        'category',
        'item',
        'unit',
        'fixed_value',
        'currently_available',
        'quarters',
        'ppmp',
        'remarks',
    ];

    protected $casts = [
        'fixed_value' => 'integer',
        'currently_available' => 'integer',

        // Generated by MySQL:
        // fixed_value - currently_available
        'total_released' => 'integer',

        'quarters' => 'array',
    ];

    public function histories(): HasMany
    {
        return $this->hasMany(
            InventoryItemHistory::class,
            'inventory_item_id'
        )->latest();
    }
}